// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: minimal.proto

package minimal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MinimalClient is the client API for Minimal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinimalClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type minimalClient struct {
	cc grpc.ClientConnInterface
}

func NewMinimalClient(cc grpc.ClientConnInterface) MinimalClient {
	return &minimalClient{cc}
}

func (c *minimalClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/minimal.Minimal/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinimalServer is the server API for Minimal service.
// All implementations must embed UnimplementedMinimalServer
// for forward compatibility
type MinimalServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedMinimalServer()
}

// UnimplementedMinimalServer must be embedded to have forward compatible implementations.
type UnimplementedMinimalServer struct {
}

func (UnimplementedMinimalServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMinimalServer) mustEmbedUnimplementedMinimalServer() {}

// UnsafeMinimalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinimalServer will
// result in compilation errors.
type UnsafeMinimalServer interface {
	mustEmbedUnimplementedMinimalServer()
}

func RegisterMinimalServer(s grpc.ServiceRegistrar, srv MinimalServer) {
	s.RegisterService(&Minimal_ServiceDesc, srv)
}

func _Minimal_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinimalServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minimal.Minimal/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinimalServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Minimal_ServiceDesc is the grpc.ServiceDesc for Minimal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Minimal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minimal.Minimal",
	HandlerType: (*MinimalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Minimal_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minimal.proto",
}
